### ISSUE TITLE
训练成本提问

### ISSUE THREAD

**Issue by mmm-cc** [bytedance/ColTrack#1]
请问在mot17和dancetrack上训练一次，分别要在什么gpu下训练多久啊

**Comment by mmm-cc** [comment]
python test.py可以多卡吗，一块A800好像显存也不够啊

**Comment by easonbyte** [comment]
我是使用8张V100训练，第一阶段很快，一两天能完成。第二阶段比较慢，mot17需要五六天的样子，Dancetrack要一周多。训练和测试都可以多卡，测试脚本可以参考[code](https://github.com/bytedance/ColTrack/blob/main/scripts/test_dancetrack_val_coltrack.sh)

**Comment by mmm-cc** [comment]
好的好的，非常感谢您的回答
